### PR TITLE
Fixed small ETA bug; Updated readme

### PR DESCRIPTION
**Pull request by andywaplinger**

### CODE REVIEW

**Comment by edward-shen** [comment]
Is it suppose to be double equals or triple equals?

**Comment by andywaplinger** [comment]
Double so that it can also catch `undefined`.

**Comment by edward-shen** [comment]
```js
!undefined; // true
!null; // true
let a = undefined;
a == null; // true
a == undefined; // true
```
`!minutes` should work perfectly though.

**Comment by andywaplinger** [comment]
Ok, I believe I've got it. `minutes` is being converted to a boolean when putting `!` in front. And at 0 minutes, `!0` means `not false` which is `true`, and so it selects the first if statement.

By instead just catching `null`, it's comparing 0 to null, which is `false`, so it goes to the next statement `0 === 0`.

**Pull request merged**
